# Generated by Django 4.2.6 on 2023-10-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(default='2001-06-26'),
            preserve_default=False,
        ),
    ]
