# Generated by Django 4.2.6 on 2023-10-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_movies_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='Movie',
        ),
    ]
